apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment }}
  labels:
    app: petclinic
  namespace: dev
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
      namespace: dev
    spec:
      containers:
      - name: {{ .Values.containerName }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP